:- module(enfermedades, [
  enfermedad/1
]).

enfermedad(gripe).
enfermedad(covid).
enfermedad(acne).
enfermedad(dermatitis_atopica).
enfermedad(dermatitis_de_contacto).
enfermedad(urticaria).
enfermedad(psoriasis).
enfermedad(varicela).
enfermedad(herpes_labial).
enfermedad(herpes_zoster).
enfermedad(tina).
enfermedad(impetigo).
enfermedad(dengue).
enfermedad(zika).
enfermedad(chikungunya).
enfermedad(mononucleosis_infecciosa).
enfermedad(tuberculosis).
enfermedad(hepatitis_a).
enfermedad(hepatitis_b).
enfermedad(sarampion).
enfermedad(rubeola).
enfermedad(paperas).

enfermedad(hipertension_arterial).
enfermedad(hipotension_arterial).
enfermedad(diabetes_tipo_1).
enfermedad(diabetes_tipo_2).
enfermedad(hipotiroidismo).
enfermedad(hipertiroidismo).
enfermedad(anemia_ferropenica).
enfermedad(obesidad).
enfermedad(hipercolesterolemia).
enfermedad(sindrome_metabolico).
enfermedad(migrana).
enfermedad(cefalea_tensional).
enfermedad(epilepsia).
enfermedad(fibromialgia).
enfermedad(artritis_reumatoide).
enfermedad(infeccion_urinaria).
enfermedad(calculos_renales).
enfermedad(conjuntivitis).
enfermedad(otitis_media).
enfermedad(otitis_externa).